//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from MapParser.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IMapParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class MapParserBaseListener : IMapParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapParserParser.map"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMap([NotNull] MapParserParser.MapContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapParserParser.map"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMap([NotNull] MapParserParser.MapContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapParserParser.fb1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFb1([NotNull] MapParserParser.Fb1Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapParserParser.fb1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFb1([NotNull] MapParserParser.Fb1Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapParserParser.datatype1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDatatype1([NotNull] MapParserParser.Datatype1Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapParserParser.datatype1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDatatype1([NotNull] MapParserParser.Datatype1Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapParserParser.comma1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComma1([NotNull] MapParserParser.Comma1Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapParserParser.comma1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComma1([NotNull] MapParserParser.Comma1Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapParserParser.datatype2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDatatype2([NotNull] MapParserParser.Datatype2Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapParserParser.datatype2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDatatype2([NotNull] MapParserParser.Datatype2Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapParserParser.lb1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLb1([NotNull] MapParserParser.Lb1Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapParserParser.lb1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLb1([NotNull] MapParserParser.Lb1Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapParserParser.name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterName([NotNull] MapParserParser.NameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapParserParser.name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitName([NotNull] MapParserParser.NameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapParserParser.ravno"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRavno([NotNull] MapParserParser.RavnoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapParserParser.ravno"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRavno([NotNull] MapParserParser.RavnoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapParserParser.new"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNew([NotNull] MapParserParser.NewContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapParserParser.new"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNew([NotNull] MapParserParser.NewContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapParserParser.hashmap"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHashmap([NotNull] MapParserParser.HashmapContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapParserParser.hashmap"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHashmap([NotNull] MapParserParser.HashmapContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapParserParser.fb2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFb2([NotNull] MapParserParser.Fb2Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapParserParser.fb2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFb2([NotNull] MapParserParser.Fb2Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapParserParser.datatype3"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDatatype3([NotNull] MapParserParser.Datatype3Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapParserParser.datatype3"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDatatype3([NotNull] MapParserParser.Datatype3Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapParserParser.comma2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComma2([NotNull] MapParserParser.Comma2Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapParserParser.comma2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComma2([NotNull] MapParserParser.Comma2Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapParserParser.datatype4"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDatatype4([NotNull] MapParserParser.Datatype4Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapParserParser.datatype4"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDatatype4([NotNull] MapParserParser.Datatype4Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapParserParser.lb2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLb2([NotNull] MapParserParser.Lb2Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapParserParser.lb2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLb2([NotNull] MapParserParser.Lb2Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapParserParser.lp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLp([NotNull] MapParserParser.LpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapParserParser.lp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLp([NotNull] MapParserParser.LpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapParserParser.rp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRp([NotNull] MapParserParser.RpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapParserParser.rp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRp([NotNull] MapParserParser.RpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapParserParser.semicolon"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSemicolon([NotNull] MapParserParser.SemicolonContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapParserParser.semicolon"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSemicolon([NotNull] MapParserParser.SemicolonContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapParserParser.dataType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDataType([NotNull] MapParserParser.DataTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapParserParser.dataType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDataType([NotNull] MapParserParser.DataTypeContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
